stages:
  - build
  - test
  - performance
  - dast
  - deploy

variables:
  EIGHTY_SIX_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:x86-$CI_COMMIT_SHA
  ARM_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:arm-$CI_COMMIT_SHA

build-86:
  tags:
    - machine
    - x86
  stage: build
  script:
    - docker login -u  $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $EIGHTY_SIX_TAG .
    - docker push $EIGHTY_SIX_TAG
  allow_failure: true

build-arm:
  tags:
    - machine
    - arm
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f DockerfilePI -t $ARM_TAG .
    - docker push $ARM_TAG

deploy-dockerhub-beta-86:
  stage: deploy
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $EIGHTY_SIX_TAG
    - docker tag $EIGHTY_SIX_TAG electricbrainuk/unraidapi:beta
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker push electricbrainuk/unraidapi:beta


deploy-dockerhub-86:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $EIGHTY_SIX_TAG
    - docker tag $EIGHTY_SIX_TAG electricbrainuk/unraidapi:latest
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker push electricbrainuk/unraidapi:latest


include:
- template: Jobs/Code-Quality.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Code-Quality.gitlab-ci.yml
- template: Jobs/Code-Intelligence.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Code-Intelligence.gitlab-ci.yml
- template: Jobs/Browser-Performance-Testing.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Browser-Performance-Testing.gitlab-ci.yml
- template: Security/DAST.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/DAST.gitlab-ci.yml
- template: Security/Container-Scanning.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Container-Scanning.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/License-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Secret-Detection.gitlab-ci.yml

