version: "3.1"

services:
  nuxt:
    build: ./app/
    container_name: unraid-api
    restart: always
    ports:
      - "3005:3005"
    command:
      "npm run start"

  nginx:
    image: nginx:1.13
    container_name: unraid-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt