name: Docker Image CI

on: 
  push: 
    branches:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: |
            git config --global user.email "bokker11@hotmail.com"
            git config --global user.name "Norbert Takács"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bokker/unraid-re:${{ env.GITHUB_REF_SLUG }}